# version: 2.1

# jobs:
#   hello-world-job:
#     docker:
#       - image: cimg/base:current
#     steps:
#       - run: echo "Hello, World!"

# workflows:
#   hello-world-workflow:
#     jobs:
#       - hello-world-job

# version: 2.1

# jobs:
#   hello-world-job:
#     docker:
#       - image: cimg/base:current
#     steps:
#       - run: echo "Hello, World!"

# workflows:
#   hello-world-workflow:
#     jobs:
#       - hello-world-job

version: 2.1

orbs:
  cypress: cypress-io/cypress@3.3.1

jobs:
  start-server:
    docker:
      - image: cypress/base: latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Start the application
          command: npm start &
workflows:
  run-tests:
    jobs:
      - start-server:
      - cypress/run:
          name: Run Cypress tests
          cypress-command: npx cypress run --component